# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db8f40fd4eaae4e58dd2f696820ebc3423558d2c6b49272a456224e4ed7afd11a10dc9f3b682f0a3741270c889bd9dafaf5aa24c9a40f37f59df6ff0a1da134

test:
  secret_key_base: 826a1945cb9d48b241c2e88bc02f332ef87eb0b5e1d449a6bc86b036d59ae77e3a577bfcb259cf7c8d2498b2c700146d66e41ea8f81dd92e60247361e8bd2401

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
